language: node

services:
  - docker

before_install:
  - rm .env
  - docker-compose down --remove-orphans
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - cp .env.example .env
  - docker-compose up

script:
  - npm run test