sudo: required
dist: bionic
language: minimal

env:
  - COMPOSE_FILE=docker-compose.test.yml

services:
  - docker
  
addons:
  apt:
    packages:
      - docker-ce
  
cache:
  bundler: true
  directories:
    - $HOME/docker

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
    
before_install:
  - >
    wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz \
    && rm dockerize-linux-amd64-v0.6.1.tar.gz
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

before_script:
  - cp .env.example .env
  - docker-compose up -d

script:
  - port=$(cat .env | grep TYPEORM_PORT= | cut -d '=' -f2)
  - dockerize -wait tcp://localhost:$port -timeout 60s npm run test
