sudo: required
dist: bionic
language: minimal

env:
  - COMPOSE_FILE=docker-compose.test.yml

services:
  - docker
  
addons:
  apt:
    packages:
      - docker-ce
  
cache:
  bundler: true
  directories:
    - $HOME/docker

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
    
before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

before_script:
  - cp .env.example .env
  - docker-compose up --build -d

script:
  - port=$(cat .env | grep TYPEORM_PORT= | cut -d '=' -f2)
  - ./wait-for-it.sh -s localhost:$port -- docker-compose run node bash -c "npm run test"
