version: '3'

services:
  mariadb:
    image: mariadb:10.4.7-bionic
    container_name: core_db
    restart: always
    env_file:
      - .env
    ports:
      - "${TYPEORM_PORT}:${TYPEORM_PORT}"
    environment:
      MYSQL_USER: ${TYPEORM_USERNAME}
      MYSQL_PASSWORD: ${TYPEORM_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${TYPEORM_PASSWORD}
      MYSQL_DATABASE: ${TYPEORM_DATABASE}
    networks:
      - core-network

  node:
    build: .
    command: npm run dev
    container_name: core_node
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - .env
    depends_on: 
      - "mariadb"
    ports:
      - "${CORE_PORT}:${CORE_PORT}"
    networks:
      - core-network
    volumes:
      - .:/user/fatapp-core/
      - /user/fatapp-core/node_modules

networks:
  core-network:
    driver: bridge