# Used for Travis-CI
version: '3'

services:
  mysql:
    image: mysql/mysql-server:5.7.24
    container_name: core_db
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    environment:
      MYSQL_USER: ${TYPEORM_USERNAME}
      MYSQL_PASSWORD: ${TYPEORM_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${TYPEORM_PASSWORD}
      MYSQL_DATABASE: ${TYPEORM_DATABASE}

  node:
    build: .
    container_name: core_node
    command: tail -F anything
    env_file:
      - .env
    depends_on: 
      - mysql
    links:
      - mysql
    ports:
      - ${CORE_PORT}:${CORE_PORT}
    volumes:
      - ./:/user/fatapp-core/
      - /user/fatapp-core/node_modules

volumes:
  db-data:
    driver: local